language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: CS_CHECK=1 STATIC_ANALYSIS=1 CODE_COVERAGE=1

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

script:
  - printenv
  - php -i

notifications:
  email: false
