#!/usr/bin/env php
<?php

require __DIR__ . '/src/Mysql.php';

$opts = \getopt('h', [
    'host:',
    'user:',
    'password:',
    'database:',
    'port:',
    'socket:',
]);
if (\array_key_exists('h', $opts)) {
    \fwrite(\STDOUT, \implode(\PHP_EOL, [
        'Usage: mysql [OPTIONS]',
        '  --host       Connect to host     [Default: INI mysqli.default_host]',
        '  --port       Port number         [Default: INI mysqli.default_port]',
        '  --user       User for login      [Default: INI mysqli.default_user]',
        '  --password   Password to use     [Default: INI mysqli.default_pw]',
        '  --database   Database to use     [Default: empty]',
        '  --socket     The socket file     [Default: INI mysqli.default_socket]',
        '',
    ]));
    exit;
}

$mysql = new \SlamMysql\Mysql(
    $opts['host'] ?? \ini_get('mysqli.default_host'),
    $opts['user'] ?? \ini_get('mysqli.default_user'),
    $opts['password'] ?? \ini_get('mysqli.default_pw'),
    $opts['database'] ?? '',
    (int) ($opts['port'] ?? \ini_get('mysqli.default_port')),
    $opts['socket'] ?? \ini_get('mysqli.default_socket'),
);
$return = $mysql->run(\STDIN, \STDOUT, \STDERR);
exit((int) (true !== $return));
