#!/usr/bin/env php
<?php

require __DIR__ . '/src/Mysql.php';

$opts = getopt('', [
    'host:',
    'username:',
    'password:',
    'database:',
    'port:',
    'socket:',
]);
$mysql = new \SlamMysql\Mysql(
    $opts['host'] ?? '',
    $opts['username'] ?? '',
    $opts['password'] ?? '',
    $opts['database'] ?? '',
    (int) $opts['port'],
    $opts['socket'] ?? '',
);
$return = $mysql->run(STDIN, STDOUT, STDERR);
exit(true === $return ? 0 : 1);
